# Setup
title:               Lanyon Blog
tagline:             'Foo Bar'
description:         'A Nice Description'
url:                 'https://a-n-t-h-o-n-y.github.io/'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Anthony Leedom
  url:               https://a-n-t-h-o-n-y.github.io/

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
